version: "3.4"
services:
  reverse-proxy:
    image: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/traefik/acme
    command:
      --providers.docker=true
      --providers.docker.exposedbydefault=false
      --entrypoints.http.address=:80
      --entrypoints.https.address=:443
      --certificatesResolvers.root.acme.httpChallenge=true
      --certificatesResolvers.root.acme.httpChallenge.entryPoint=http
      --certificatesresolvers.root.acme.email=d.tarasov@fatalist.tech

  chat:
    build:
      context: ./src/Chat
      target: release
    image: docker.io/fatalist/fatalist.tech-chat:alpine
    environment:
      ASPNETCORE_URLS: http://+
      ASPNETCORE_ENVIRONMENT: Release
      ASPNETCORE_BEHIND_HTTPS_PROXY: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.chat-ssl.headers.framedeny=true"
      - "traefik.http.middlewares.chat-ssl.headers.sslredirect=true"
      - "traefik.http.middlewares.chat-stripprefix.stripprefix.prefixes=/api/chat"
      - "traefik.http.routers.chat.rule=(Host(`fatalist.tech`) || Host(`www.fatalist.tech`)) && PathPrefix(`/api/chat`)"
      - "traefik.http.routers.chat.entrypoints=https"
      - "traefik.http.routers.chat.middlewares=chat-stripprefix,chat-ssl"
      - "traefik.http.routers.chat.tls.certresolver=root"

  app:
    build:
      context: ./src/App
      target: release
    image: docker.io/fatalist/fatalist.tech-app:alpine
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.app-ssl.headers.framedeny=true"
      - "traefik.http.middlewares.app-ssl.headers.sslredirect=true"
      - "traefik.http.routers.app.rule=Host(`fatalist.tech`) && PathPrefix(`/`)"
      - "traefik.http.routers.app.entrypoints=https"
      - "traefik.http.routers.app.tls.certresolver=root"
      - "traefik.http.routers.app.middlewares=app-ssl"
      - "traefik.http.routers.app-http.rule=Host(`fatalist.tech`) && PathPrefix(`/`)"
      - "traefik.http.routers.app-http.entrypoints=http"
      - "traefik.http.routers.app-http.middlewares=app-ssl"
